### ISSUE TITLE
Port this repository from PNaCl to WebAssembly

### ISSUE THREAD

**Issue by gogins** [gogins/gogins.github.io#14]
Do this in parallel, then if it works well enough for live audio, remove the PNaCl stuff.

**Comment by gogins** [comment]
I put in `minimal.html.` Not every run works, but some runs work just fine. There are some issues:
1. The wasm file needs to be in the Web page's directory. It should be OK for it to be in a 'wasm' subdirectory.
2. I started porting `Scrims_wasm.html` and got this: 
```
Uncaught RuntimeError: integer result unrepresentable
    at _process_rt_event (<WASM>[493]+119)
    at _sensevents (<WASM>[490]+1900)
    at dynCall_ii (<WASM>[5287]+13)
    at Object.Module.dynCall_ii (http://localhost:8080/wasm/libcsound.js:9523:89)
    at invoke_ii (http://localhost:8080/wasm/libcsound.js:9007:32)
    at _csoundPerformKsmps (<WASM>[294]+462)
    at _CsoundObj_performKsmps (<WASM>[154]+33)
    at Module._CsoundObj_performKsmps (http://localhost:8080/wasm/libcsound.js:9513:128)
    at ScriptProcessorNode.audioProcessNode.onaudioprocess (http://localhost:8080/wasm/CsoundObj.js:289:20)
_process_rt_event
_sensevents
dynCall_ii
Module.dynCall_ii @ libcsound.js:9523
invoke_ii @ libcsound.js:9007
_csoundPerformKsmps
_CsoundObj_performKsmps
Module._CsoundObj_performKsmps @ libcsound.js:9513
audioProcessNode.onaudioprocess @ CsoundObj.js:289
```
It seems @hfmanson has seen similar issues. I have to try to examine the wasm code itself and see if I can figure just where in the C code this is happening.

**Comment by gogins** [comment]
Perhaps this macro `MYFLT2LONG` can be used if I can find out where to use it.

**Comment by hfmanson** [comment]
My last wasm version of csound fixed the MYFLT2LONG macro to include
boundary checks. floats that are not representable as integers cause
WebAssembly traps

**Comment by gogins** [comment]
Indeed, I already got rid of the trap (the diff is below). Your comments on
StackOverflow helped.

diff --git a/Engine/musmon.c b/Engine/musmon.c
index 948d620..63c0729 100644
--- a/Engine/musmon.c
+++ b/Engine/musmon.c
@@ -859,7 +859,9 @@ static int process_rt_event(CSOUND *csound, int
sensType)
       EVTNODE *e = csound->OrcTrigEvts;
       /* RM: Events are sorted on insertion, so just check the first */
       evt = &(e->evt);
-      insno = (int)(evt->p[1]);
+      /// MKG: Trying rounding with precision here to avoid trap in
JavaScript.
+      /// insno = (int)(evt->p[1]);
+      insno = MYFLT2LONG(evt->p[1]);
       if ((rfd = getRemoteInsRfd(csound, insno))) {
         if (rfd == GLOBAL_REMOT)
           insGlobevt(csound, evt);       /* RM: do a global send and allow
local */



-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
There are still issues. My piece **_Scrims_**, ported to WASM, does not produce sound and soon runs out of memory. It might be the way this piece routes audio, I will try to port **_Unperformed Experiments Have No Results_**.

**Comment by hfmanson** [comment]
Hello Michael,

If you trust me, just sent 'Scrims' to me, i'll keep it to myself just to
find the problem;)

**Comment by gogins** [comment]
I think I am making some progress on this. The levels have to be adjusted
and then something has to be done to force stereo rather than mono.


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
After adding `nchnls=2` and boosting the output level correction factor, `Scrims_wasm.html` works fine!

**Comment by gogins** [comment]
I don't actually need to do this... just make sure new pieces are for WASM and also work with csound.node.
