### ISSUE TITLE
Assure stability of CsoundQt with HTML5

### ISSUE THREAD

**Issue by gogins** [gogins/gogins.github.io#20]
If there continues to be problems with the stability of CsoundQt, work with @tarmoj to ensure that stability is adequate on Linux, Windows, and OS X, including with the HTML5 features.

This concern arises from complaints from students relayed by their teachers, which I heard about at the 2017 International Csound Conference.

**Comment by gogins** [comment]
It's bad that the CsoundQt repo is within the Csound repo for the AppVeyor style local build. This means updating CsoundQt is more or less impossible.

It's worse that Anaconda2 unilaterally decided to host the only valid Qt SDK on my PC.

I have created a .usr.pri file for doing my local CsoundQt build. This seems to solve both the above issues.

The crash occurs when the record condition variable is signaled but does not appear to be valid.

I'm trying to see if a complete rebuild helps with that. I need to check if all DLLs are loaded from all the right places.

**Comment by gogins** [comment]
With a clean rebuild and the correct binary paths, the current AppVeyor build in the master branch of CsoundQt is stable. I will leave this open but not work on it until the master branch has been merged back into develop.

**Comment by tarmoj** [comment]
Hi,
I finalized master branch for 0.9.5 (added release notes and tag 0.9.5), merged last changes back to develop. Please use master branch for installer build and I will do all upcoming work on develop bracnh.
tarmo

**Comment by gogins** [comment]
That's much appreciated, and I will test this in the next few days.

Best,
Mike

**Comment by gogins** [comment]
I will do my local build with the develop branch of CsoundQt.

**Comment by gogins** [comment]
I am cloning CsoundQt outside the Csound tree so I can checkout branches and pull updates. I will make a link from inside the Csound tree for building.

**Comment by gogins** [comment]
This now seems to be under control, so I am closing again. I will try to update my laptop to Windows 8.1, if that is still possible, otherwise I will just live with this situation.

**Comment by gogins** [comment]
Using a link doesn't work. I just cloned the develop branch for my local build.

**Comment by gogins** [comment]
Seems much better for me. Waiting for more feedback before closing this.

**Comment by gogins** [comment]
No feedback. Works for me so closing.
