### ISSUE TITLE
Enable Faust opcodes for csound.node

### ISSUE THREAD

**Issue by gogins** [gogins/gogins.github.io#25]
The Russian bell example in Faust is enough to make me want this.

I can build libfaustcsound.so but but it crashes. 

libfaustcsound.so:                 U _ZTIN4llvm11ObjectCacheE (typeinfo for llvm::ObjectCache)
libfaustcsound.so:0000000001d991f8 D _ZTVN4llvm11ObjectCacheE (vtable for llvm::ObjectCache, NOT RELEVANT)
/usr/local/lib/libfaust.a:llvm_dsp_aux.o:                 U _ZTIN4llvm11ObjectCacheE (typeinfo for llvm::ObjectCache)

NOT defined in LLVM 5.
NOT defined in LLVM 4.

It looks like LLVM is built without runtime type information but Faust is built WITH runtime type information.

I will simply try rebuilding Faust without RTTI.

**Comment by gogins** [comment]
Building Faust without RTTI reveals that Faust requires RTTI. That means I cannot use Faust without building LLVM from sources. That is truly a drag.

**Comment by gogins** [comment]
I am building LLVM 3.7.1 with RTTI and it works fine. I am using the 
following flags:

         cmake \
             -DCMAKE_BUILD_TYPE=Release \
             -DCMAKE_INSTALL_PREFIX=$(LLVM_DST) \
             -DLLVM_BUILD_TOOLS=OFF \
             -DLLVM_ENABLE_ASSERTIONS=ON \
             -DLLVM_ENABLE_RTTI=ON \
             -DLLVM_ENABLE_WERROR=ON \
             -DLLVM_REQUIRES_RTTI=ON \
             -DLLVM_TARGETS_TO_BUILD="X86" \
             -DLLVM_TARGET_ARCH="X86" \
             $(LLVM_SVN)

You apparently need to both use  LLVM_ENABLE_RTTI=ON and 
LLVM_REQUIRES_RTTI=ON.

**Comment by gogins** [comment]
I will try turning off RTTI only for:

g++ -fno-rtti -std=gnu++11 -O1 -fPIC -D__USE_MINGW_ANSI_STDIO -Wall -Wuninitialized -Wno-parentheses -Wno-overloaded-virtual -fvisibility=hidden -I. -Iboxes -Ierrors -Ievaluate -Inormalize -Iparser -Ipropagate -Iparallelize -Isignals -Itlib -Idraw -Idraw/device -Idraw/schema -Iextended -Ipatternmatcher -Idocumentator -Iutils -I../libraries -Igenerator -Igenerator/asmjs -Igenerator/c -Igenerator/cpp -Igenerator/java -Igenerator/js -Igenerator/llvm -Igenerator/fir -Igenerator/wasm -Igenerator/interpreter -Igenerator/rust -DINSTALL_PREFIX='"/usr/local"' -I`/usr/local/bin/llvm-config --includedir` -I../architecture -DLLVM_40 -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS  -DASMJS_BUILD -DC_BUILD -DCPP_BUILD -DFIR_BUILD -DINTERP_BUILD -DJAVA_BUILD -DJS_BUILD -DLLVM_BUILD -DOCPP_BUILD -DRUST_BUILD -DWASM_BUILD -O3   -c -o generator/llvm/llvm_dsp_aux.o generator/llvm/llvm_dsp_aux.cpp

No, that does not work because there are many dynamic_casts that quit compiling.

**Comment by gogins** [comment]
I will continue to pursue the faust opcodes when I get back on Linux. 
In the meantime, I will see if I can generate Csound opcodes using Faust Live.

**Comment by gogins** [comment]
It will do it but not nicely. Haven't tested Csound opcode thus generated but it builds with:

cl blowBottle_linux_csound-64bits.cpp /Ox /DUSE_DOUBLE /IC:/Program_Files/Csound_x64/include/csound /LD /link /out:blow_bottle.dll

And it loads. Will test tomorrow. Code has to be patched to give zero-size arrays one element, and to provide a real opcode name. I can probably come with a script to do a better job.

FaustLive examples sound very good so this is indeed worth pursuing. Having the Faust opcodes proper would be even better. I am impressed with the science and the art but not with the housekeeping department of the software engineering.

**Comment by gogins** [comment]
At this point the objective is to produce a .cpp file from the online Faust compiler and then pop it into a tool that will produce a Csound plugin opcode.

**Comment by gogins** [comment]
The online Faust Editor is useless because it does not export C++ source code.

**Comment by gogins** [comment]
There is no option on FaustLive or the Faust Editor (that I can find, anyway) to export just the DSP factory. It looks like I have to either download vanilla Faust and use that, or use FaustLive and export Csound opcode code and patch it. I'll try with vanilla Faust.

**Comment by gogins** [comment]
No, the Faust master branch doesn't compile with MSVS, it seems clear that the WIndows build of the project has not been maintained.

**Comment by gogins** [comment]
At this time, the only way for me to use Faust is to run FaustLive and save source code for a Csound 64 bit sample size opcode, and compile it. I will now see if that works.

In the future, I can try to build LLVM with RTTI and Faust on Linux again.

**Comment by sletz** [comment]
We are working on a cmake based build system for Faust, hopefully improving the " it seems clear that the WIndows build of the project has not been maintained." issue, and possibly the LLVM with RTTI one also.

**Comment by gogins** [comment]
That would be great, thanks.

Mike
